apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
spec:
  containers:
    - name: nginx-test-pod-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx
        - name: htpasswd-volume
          mountPath: /etc/nginx/conf
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-conf
    - name: htpasswd-volume
      secret:
        secretName: nginx-password