version: "3.8"
services:

  voting_app:
    image: dockersamples/examplevotingapp_vote:before
    deploy:
      replicas: 5
    networks:
      - frontend_ntw
    ports:
      - 5000:80

  redis:
    image: redis:3.2
    deploy:  
      replicas: 5
  
  vote_worker:
    image: dockersamples/examplevotingapp_worker:latest
    deploy:
      replicas: 1
  
  postgres_db:
    image: postgres:9.4
    deploy:
      replicas: 1
    networks:
      - backend_ntw
    volumes:
      - type: bind
        source: ./db_store
        target: /var/lib/postgresql/data:
  
  result_app:
    image: dockersamples/examplevotingapp_result:bfore
    deploy:
      replicas: 1
    networks: 
      - backend_ntw
    ports:
      - 5001:80

networks:
    frontend_ntw:
    backend_ntw:
