apiVersion: v1
kind: Pod
metadata: 
  name: nginx-test
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: secret-test
        mountPath: secret-key
  volumes:
    - name: secret-test
      secret:
        secretName: password